LABEL  "com.github.actions.name" = "Hello World" 
LABEL  "com.github.actions.description" = "Ecrire des arguments dans la sortie standard" 
LABEL  "com.github.actions.icon" = "mic" 
LABEL  " com.github.actions.color " = " violet "

LABEL  "repository" = "http://github.com/octocat/hello-world" 
LABEL  "homepage" = "http://github.com/actions" 
LABEL  "mainter " = "Octocat <octocat@github.com> "

ADD entrypoint.sh /entrypoint.sh
 RUN chmod + x /entrypoint.sh
 ENTRYPOINT [ "/entrypoint.sh" ]
